# Generated by Django 2.1.7 on 2019-02-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cats',
            old_name='name',
            new_name='nickname',
        ),
    ]
