# Generated by Django 2.1.7 on 2019-02-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20190226_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='foods',
            field=models.CharField(default='--', max_length=300),
            preserve_default=False,
        ),
    ]
