# Generated by Django 2.1.7 on 2019-03-18 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='iso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unesco.Iso'),
        ),
    ]
