# Generated by Django 2.1.7 on 2019-03-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0002_auto_20190318_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.CharField(default='-', max_length=128),
            preserve_default=False,
        ),
    ]
