# Generated by Django 2.1.7 on 2019-03-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0004_auto_20190321_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='area_hectares',
            field=models.FloatField(max_length=128, null=True),
        ),
    ]
